package component:base64;

world base64 {
    /// Encode bytes into a base64 string
    export encode: func(input: list<u8>) -> string;
    /// Decode a base64 string into bytes
    export decode: func(input: string) -> result<list<u8>, string>;
}
